### ISSUE TITLE
Decide CLI Tool

### ISSUE THREAD

**Issue by gerred** [gerred/kube-cluster#1]
We need to decide a CLI tool.

Some options:
Built in os.Flag, simplest and no dependencies.
https://github.com/codegangsta/cli
https://github.com/mitchellh/cli
https://github.com/spf13/cobra
https://github.com/alecthomas/kingpin

Right now, I really like kingpin and cobra, but I'm open.

**Comment by arschles** [comment]
I've only used https://github.com/codegangsta/cli and https://github.com/mitchellh/cli and either have met all my needs.

**Comment by ucirello** [comment]
I have tried both https://github.com/codegangsta/cli and  https://github.com/spf13/cobra 

I think cobra has a slightly more comfortable API than codegangsta/cli

I would go for cobra.

**Comment by gerred** [comment]
Going with cobra for now, and we can evaluate further. I did an initial run with it and it felt the best. I've also talked with Steve Francia (spf13) a bit about configuration, since we're going to have flags based on driver/provisioner, and his recommendation was also using Viper with it.
