### ISSUE TITLE
Fix redundancies in README.md

### ISSUE THREAD

**Issue by gerred** [gerred/kube-cluster#7]
Currently, there's a few redundancies in the API.

`kube-cluster create env dev` could be a little more clear as just `kube-cluster create dev`, and have env as a top level command for getting the current env.

Also, `kubectl.sh` is being replaced by `kubectl`. We may even be able to just include kubernetes as a dependency, so that a user isn't required to have the kubectl binary installed to use kube-cluster.

Thoughts @ccirello?

**Comment by ucirello** [comment]
> kube-cluster create env dev could be a little more clear as just kube-cluster create dev, and have env as a top level command for getting the current env.

this breaks with the concept of kube-cluster being a wrapper around kubectl. 

Kubectl tell resources apart by a subcommand, thus, if in kubectl we've got `kubectl create pod`, in kube-cluster we'd need to achieve similar interface `kube-cluster create [what] [name]`.

**Comment by gerred** [comment]
Moving to this a PR shortly. What about `kube-cluster ctl create` for commands that pass through to kubectl?

**Comment by ucirello** [comment]
> Also, kubectl.sh is being replaced by kubectl. We may even be able to just include kubernetes as a dependency, so that a user isn't required to have the kubectl binary installed to use kube-cluster.

My bad, I forgot to replace them.

**Comment by ucirello** [comment]
> Moving to this a PR shortly. What about kube-cluster ctl create for commands that pass through to kubectl?

It is a more verbose alternative in IMHO. I was really thinking about of testing if the subcommand was targeting a cluster, and if not, just forward to kubectl.

**Comment by gerred** [comment]
Ah, I see what you're saying. Ok, I'm down with that. What do you think about bringing in kubernetes as a dependency and relieving the requirement of having kubectl on the system? That way we don't have version conflicts when kubectl updates, and instead ship a new kube-cluster binary.

**Comment by ucirello** [comment]
> What do you think about bringing in kubernetes as a dependency and relieving the requirement of having kubectl on the system?

Just done before merging

**Comment by gerred** [comment]
Great, closing this issue.
